-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'acef229eefb088f9' HASH '15ad15949a5535b8dc0595597f78e572dea4f9260b023e55d7f5a14b8a9255c2' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."BOARDGAME_COPIES"(
    "COPY_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "BOARDGAME_ID" BIGINT NOT NULL,
    "OWNER_ID" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."BOARDGAME_COPIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("COPY_ID");        
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BOARDGAME_COPIES;        
INSERT INTO "PUBLIC"."BOARDGAME_COPIES" VALUES
(1, 1, 1),
(2, 2, 1);        
CREATE MEMORY TABLE "PUBLIC"."BOARDGAME_USERS"(
    "BOARDGAME_USER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);         
ALTER TABLE "PUBLIC"."BOARDGAME_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("BOARDGAME_USER_ID");               
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.BOARDGAME_USERS;         
INSERT INTO "PUBLIC"."BOARDGAME_USERS" VALUES
(1, 'ryanvankriekinge@example.com', 'Ryan Vankriekinge'),
(2, 'henkdevos@example.com', 'Henk De Vos'),
(3, 'alice.martin@example.com', 'Alice Martin'),
(4, 'bob.johnson@example.com', 'Bob Johnson'),
(5, 'carla.smith@example.com', 'Carla Smith'),
(6, 'david.lee@example.com', 'David Lee'),
(7, 'emma.brown@example.com', 'Emma Brown');
CREATE MEMORY TABLE "PUBLIC"."BOARDGAMES"(
    "BOARDGAME_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "BGG_ID" CHARACTER VARYING(255),
    "BGGURL" CHARACTER VARYING(255),
    "IMAGEURL" CHARACTER VARYING(255),
    "MAX_PLAYERS" INTEGER NOT NULL,
    "MIN_PLAYERS" INTEGER NOT NULL,
    "PUBLISHER" CHARACTER VARYING(255) NOT NULL,
    "RELEASE_YEAR" INTEGER NOT NULL,
    "TITLE" CHARACTER VARYING(255) NOT NULL,
    "POPULARITY" INTEGER NOT NULL
);          
ALTER TABLE "PUBLIC"."BOARDGAMES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("BOARDGAME_ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.BOARDGAMES;              
INSERT INTO "PUBLIC"."BOARDGAMES" VALUES
(1, '387378', 'https://boardgamegeek.com/boardgame/387378/mlem-space-agency', 'https://cf.geekdo-images.com/CQ9o1kqExmBpHcPMVk0qwQ__imagepage/img/z6hmRBJb8Tv4t5n5N0UEzXIfAl0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7926071.jpg', 5, 2, 'Rebel Studio', 2024, 'MLEM: Space Agency', 45),
(2, '6249', 'https://boardgamegeek.com/boardgame/6249/alhambra', 'https://cf.geekdo-images.com/OiqKsYDh7pqeRYKG__kMSw__itemrep/img/7RUFLxeNec7dSbH0d_t77bFj3mo=/fit-in/246x300/filters:strip_icc()/pic4893652.jpg', 6, 2, 'Queen Games', 2003, 'Alhambra', 6),
(3, '14996', 'https://boardgamegeek.com/boardgame/14996/ticket-to-ride-europe', 'https://cf.geekdo-images.com/0K1AOciqlMVUWFPLTJSiww__itemrep/img/D9gFnF3e-NXcVjvkNUsn19C7cHQ=/fit-in/246x300/filters:strip_icc()/pic66668.jpg', 5, 2, 'Days of Wonder', 2005, 'Ticket to Ride: Europe', 89),
(4, '217', 'https://boardgamegeek.com/boardgame/217/a-la-carte', 'https://cf.geekdo-images.com/BvXlvPrfHf-6Mhmthc3kJg__itemrep/img/S5gBaTeskxgvJwXUESQDYUqudXo=/fit-in/246x300/filters:strip_icc()/pic599251.jpg', 4, 2, 'Heidelberg Spieleverlag', 1989, 'A la carte', 45),
(5, '70919', 'https://boardgamegeek.com/boardgame/70919/takenoko', 'https://cf.geekdo-images.com/uvz-5V6A2R6dp2oWIXmj_g__itemrep/img/fT5tXhYc0kc5ur8NDdnJHj_GOSw=/fit-in/246x300/filters:strip_icc()/pic1912529.jpg', 4, 2, 'Bombyx', 2011, 'Takenoko', 22),
(6, '201808', 'https://boardgamegeek.com/boardgame/201808/clank-a-deck-building-adventure', 'https://cf.geekdo-images.com/DPjV1iI0ygo5Bl3XLNRiIg__itemrep/img/pdioRYjmiownDyFOmbIy-aC5kfU=/fit-in/246x300/filters:strip_icc()/pic4449526.jpg', 4, 2, 'Dire Wolf', 2016, 'Clank!', 35),
(7, '392023', 'https://boardgamegeek.com/boardgame/392023/mycelia', 'https://cf.geekdo-images.com/P8-3HeCgEa_CODQiQxq9SQ__itemrep/img/F_6OA7E_-sI8Qx5wQUYj4SGFcak=/fit-in/246x300/filters:strip_icc()/pic7849476.jpg', 4, 1, 'Ravensburger', 2023, 'Mycelia', 145),
(8, '13', 'https://boardgamegeek.com/boardgame/13/catan', 'https://cf.geekdo-images.com/PyUol9QxBnZQCJqZI6bmSA__itemrep/img/zUs-jB7S9JTuLPOcY9pUxaqYNqA=/fit-in/246x300/filters:strip_icc()/pic8632666.png', 4, 3, 'KOSMOS', 1995, 'Catan', 78);
CREATE MEMORY TABLE "PUBLIC"."LENDINGS"(
    "LOAN_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) NOT NULL,
    "LOAN_DEADLINE" TIMESTAMP(6) NOT NULL,
    "LOAN_TIMESTAMP" TIMESTAMP(6) NOT NULL,
    "RETURNED_AT" TIMESTAMP(6),
    "BORROWER_ID" BIGINT NOT NULL,
    "COPY_ID" BIGINT NOT NULL,
    "STATUS_ID" BIGINT NOT NULL
);     
ALTER TABLE "PUBLIC"."LENDINGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A1" PRIMARY KEY("LOAN_ID");               
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.LENDINGS;
INSERT INTO "PUBLIC"."LENDINGS" VALUES
(1, TIMESTAMP '2025-09-01 12:00:00', TIMESTAMP '2025-08-17 15:09:35.297737', NULL, 1, 1, 1);          
CREATE MEMORY TABLE "PUBLIC"."LOAN_STATUSES"(
    "STATUS_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "STATUS_CODE" CHARACTER VARYING(255) NOT NULL,
    "STATUS_TEXT" CHARACTER VARYING(255) NOT NULL
);      
ALTER TABLE "PUBLIC"."LOAN_STATUSES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("STATUS_ID");         
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.LOAN_STATUSES;           
INSERT INTO "PUBLIC"."LOAN_STATUSES" VALUES
(1, 'ONGOING', 'Borrower is still lending the boardgame.'),
(2, 'RETURNED', 'Borrower returned the boardgame.');
ALTER TABLE "PUBLIC"."LOAN_STATUSES" ADD CONSTRAINT "PUBLIC"."UKAOA1P2RGUTCWHLFNHQA4TK0JK" UNIQUE NULLS DISTINCT ("STATUS_CODE");             
ALTER TABLE "PUBLIC"."BOARDGAME_USERS" ADD CONSTRAINT "PUBLIC"."UKDP5M51C8T1SD5NJCWIRIV7RYE" UNIQUE NULLS DISTINCT ("EMAIL"); 
ALTER TABLE "PUBLIC"."LENDINGS" ADD CONSTRAINT "PUBLIC"."FK4S1JICSS3WQ0X4OT52S25A420" FOREIGN KEY("BORROWER_ID") REFERENCES "PUBLIC"."BOARDGAME_USERS"("BOARDGAME_USER_ID") NOCHECK;          
ALTER TABLE "PUBLIC"."BOARDGAME_COPIES" ADD CONSTRAINT "PUBLIC"."FK93XEVBDB58KENPNOHMG49P8Q6" FOREIGN KEY("BOARDGAME_ID") REFERENCES "PUBLIC"."BOARDGAMES"("BOARDGAME_ID") NOCHECK;           
ALTER TABLE "PUBLIC"."LENDINGS" ADD CONSTRAINT "PUBLIC"."FKA5LRWHPAI2VFSAVG5Q9PR823D" FOREIGN KEY("COPY_ID") REFERENCES "PUBLIC"."BOARDGAME_COPIES"("COPY_ID") NOCHECK;       
ALTER TABLE "PUBLIC"."BOARDGAME_COPIES" ADD CONSTRAINT "PUBLIC"."FKH7UMLWADSO46C2ON2XH7TJJ8U" FOREIGN KEY("OWNER_ID") REFERENCES "PUBLIC"."BOARDGAME_USERS"("BOARDGAME_USER_ID") NOCHECK;     
ALTER TABLE "PUBLIC"."LENDINGS" ADD CONSTRAINT "PUBLIC"."FKTRGLAFSPK5QWQ5U9FSN9ADRUW" FOREIGN KEY("STATUS_ID") REFERENCES "PUBLIC"."LOAN_STATUSES"("STATUS_ID") NOCHECK;

INSERT INTO "PUBLIC"."BOARDGAME_COPIES" ("BOARDGAME_ID", "OWNER_ID") VALUES
                                                                         (3, 2),
                                                                         (4, 3),
                                                                         (5, 4),
                                                                         (6, 5),
                                                                         (7, 6),
                                                                         (8, 7),
                                                                         (1, 3),
                                                                         (2, 5),
                                                                         (3, 1),
                                                                         (4, 2);


INSERT INTO "PUBLIC"."LENDINGS" ("LOAN_DEADLINE", "LOAN_TIMESTAMP", "RETURNED_AT", "BORROWER_ID", "COPY_ID", "STATUS_ID") VALUES
                                                                                                                              (TIMESTAMP '2025-08-25 12:00:00', TIMESTAMP '2025-08-18 10:00:00', NULL, 4, 3, 1),
                                                                                                                              (TIMESTAMP '2025-08-30 12:00:00', TIMESTAMP '2025-08-17 16:30:00', NULL, 5, 5, 1),
                                                                                                                              (TIMESTAMP '2025-09-05 12:00:00', TIMESTAMP '2025-08-18 09:15:00', NULL, 2, 2, 1),
                                                                                                                              (TIMESTAMP '2025-08-28 12:00:00', TIMESTAMP '2025-08-17 14:45:00', TIMESTAMP '2025-08-18 12:00:00', 3, 4, 2);
