SET search_path TO public;

;             
CREATE TABLE boardgame_copies(
    copy_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    boardgame_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL
);       
ALTER TABLE boardgame_copies ADD CONSTRAINT constraint_a PRIMARY KEY(copy_id);        
-- 2 +/- SELECT COUNT(*) FROM BOARDGAME_COPIES;        
INSERT INTO boardgame_copies VALUES
(1, 1, 1),
(2, 2, 1);        
CREATE TABLE boardgame_users(
    boardgame_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email CHARACTER VARYING(255) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL
);         
ALTER TABLE boardgame_users ADD CONSTRAINT constraint_f PRIMARY KEY(boardgame_user_id);               
-- 2 +/- SELECT COUNT(*) FROM BOARDGAME_USERS;         
INSERT INTO boardgame_users VALUES
(1, 'ryanvankriekinge@example.com', 'Ryan Vankriekinge'),
(2, 'henkdevos@example.com', 'Henk De Vos');        
CREATE TABLE boardgames(
    boardgame_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bgg_id CHARACTER VARYING(255),
    bggurl CHARACTER VARYING(255),
    imageurl CHARACTER VARYING(255),
    max_players INTEGER NOT NULL,
    min_players INTEGER NOT NULL,
    publisher CHARACTER VARYING(255) NOT NULL,
    release_year INTEGER NOT NULL,
    title CHARACTER VARYING(255) NOT NULL,
    popularity INTEGER NOT NULL
);          
ALTER TABLE boardgames ADD CONSTRAINT constraint_8 PRIMARY KEY(boardgame_id);         
-- 3 +/- SELECT COUNT(*) FROM BOARDGAMES;              
INSERT INTO boardgames VALUES
(1, '387378', 'https://boardgamegeek.com/boardgame/387378/mlem-space-agency', 'https://cf.geekdo-images.com/CQ9o1kqExmBpHcPMVk0qwQ__imagepage/img/z6hmRBJb8Tv4t5n5N0UEzXIfAl0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic7926071.jpg', 5, 2, 'Rebel Studio', 2024, 'MLEM: Space Agency', 0),
(2, '6249', 'https://boardgamegeek.com/boardgame/6249/alhambra', 'https://cf.geekdo-images.com/OiqKsYDh7pqeRYKG__kMSw__itemrep/img/7RUFLxeNec7dSbH0d_t77bFj3mo=/fit-in/246x300/filters:strip_icc()/pic4893652.jpg', 6, 2, 'Queen Games', 2003, 'Alhambra', 0),
(3, '14996', 'https://boardgamegeek.com/boardgame/14996/ticket-to-ride-europe', 'https://cf.geekdo-images.com/0K1AOciqlMVUWFPLTJSiww__itemrep/img/D9gFnF3e-NXcVjvkNUsn19C7cHQ=/fit-in/246x300/filters:strip_icc()/pic66668.jpg', 5, 2, 'Days of Wonder', 2005, 'Ticket to Ride: Europe', 0);          
CREATE TABLE lendings(
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loan_deadline TIMESTAMP(6) NOT NULL,
    loan_timestamp TIMESTAMP(6) NOT NULL,
    returned_at TIMESTAMP(6),
    borrower_id BIGINT NOT NULL,
    copy_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL
);     
ALTER TABLE lendings ADD CONSTRAINT constraint_a1 PRIMARY KEY(loan_id);               
-- 1 +/- SELECT COUNT(*) FROM LENDINGS;
INSERT INTO lendings VALUES
(1, TIMESTAMP '2025-09-01 12:00:00', TIMESTAMP '2025-08-17 15:09:35.297737', NULL, 1, 1, 1);          
CREATE TABLE loan_statuses(
    status_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_code CHARACTER VARYING(255) NOT NULL,
    status_text CHARACTER VARYING(255) NOT NULL
);      
ALTER TABLE loan_statuses ADD CONSTRAINT constraint_e PRIMARY KEY(status_id);         
-- 2 +/- SELECT COUNT(*) FROM LOAN_STATUSES;           
INSERT INTO loan_statuses VALUES
(1, 'ONGOING', 'Borrower is still lending the boardgame.'),
(2, 'RETURNED', 'Borrower returned the boardgame.');
ALTER TABLE loan_statuses ADD CONSTRAINT ukaoa1p2rgutcwhlfnhqa4tk0jk UNIQUE (status_code);             
ALTER TABLE boardgame_users ADD CONSTRAINT ukdp5m51c8t1sd5njcwiriv7rye UNIQUE (email); 
ALTER TABLE lendings ADD CONSTRAINT fk4s1jicss3wq0x4ot52s25a420 FOREIGN KEY(borrower_id) REFERENCES boardgame_users(boardgame_user_id);          
ALTER TABLE boardgame_copies ADD CONSTRAINT fk93xevbdb58kenpnohmg49p8q6 FOREIGN KEY(boardgame_id) REFERENCES boardgames(boardgame_id);           
ALTER TABLE lendings ADD CONSTRAINT fka5lrwhpai2vfsavg5q9pr823d FOREIGN KEY(copy_id) REFERENCES boardgame_copies(copy_id);       
ALTER TABLE boardgame_copies ADD CONSTRAINT fkh7umlwadso46c2on2xh7tjj8u FOREIGN KEY(owner_id) REFERENCES boardgame_users(boardgame_user_id);     
ALTER TABLE lendings ADD CONSTRAINT fktrglafspk5qwq5u9fsn9adruw FOREIGN KEY(status_id) REFERENCES loan_statuses(status_id);      