### Create a new user
POST http://localhost:8080/api/boardgameUsers
Content-Type: application/json

{
  "name": "Ryan Vankriekinge",
  "email": "ryanvankriekinge@example.com"
}

### Create a new user
POST http://localhost:8080/api/boardgameUsers
Content-Type: application/json

{
  "name": "Henk De Vos",
  "email": "henkdevos@example.com"
}


### Get a user by ID
GET http://localhost:8080/api/boardgameUsers/1