### Get copy by ID
GET http://localhost:8080/api/boardgameCopies/1

### Get all copies
GET http://localhost:8080/api/boardgameCopies

### Create copy 1
POST http://localhost:8080/api/boardgameCopies
Content-Type: application/json

{
  "boardgameId": 1,
  "ownerId": 1
}

### Create copy 2
POST http://localhost:8080/api/boardgameCopies
Content-Type: application/json

{
  "boardgameId": 2,
  "ownerId": 1
}
