POST http://localhost:8080/api/lendings
Content-Type: application/json

{
  "copyId": 1,
  "borrowerId": 1,
  "loanDeadline": "2025-09-01T12:00:00",
  "statusId": 1
}

### Return lending
PUT http://localhost:8080/api/lendings/1/return
Accept: application/json